# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: scheduler_app_development
  username: shezonia
  password: database
  host: localhost
  port: 5432

test:
  <<: *default
  database: scheduler_app_test
  username: shezonia
  password: database
  host: localhost
  port: 5432

production:
  <<: *default
  database: scheduler_app_production
  username: shezonia
  password: database
  host: localhost
  port: 5432
